### ISSUE TITLE
How to obtain the tag of a cell?

### ISSUE THREAD

**Issue by LiangKuan4451** [ONLYOFFICE/DocumentServer#2929]
Do you want to: Suggest a feature
Document Server version: 8.2 Community Edition

For example, as shown in the figure below, I have three cells. I tried to obtain the tag of the first cell using the following code according to the Office API.
The result is not a function.

```
let oDocument = Api.GetDocument();

let oTable = oDocument.GetAllTablesOnPage(0)[0];

let oTableCell = oTable.GetCell(0,0). GetContent(). GetElement(0). GetTag();

console.log("oTableCell", oTableCell);
// oTable. GetCell(...). GetContent(...). GetElement(...). GetTag is not a function
```

![QQ截图20241021192743](https://github.com/user-attachments/assets/772d3609-3e25-4244-b8a9-5b3c0a316101)

There are even more strange issues, such as the image I uploaded, where you can see that the third cell is an image.
I can use version 7.1
```
oTable.GetCell(0,2). GetContent(). GetElement(0). GetTag();
```
Retrieve the tag of the image
But after updating to 8.2, it also became
```
oTable.GetCell(...). GetContent(...). GetElement(...). GetTag is not a function
```
How can I obtain the tag of a cell in version 8.2?

**Comment by lemonowl** [comment]
Hi, @LiangKuan4451!
I apologize, but I'm not sure that I fully understand your issue.
GetTag method is only available for [ApiInlineLvlSdt](https://api.onlyoffice.com/officeapi/textdocumentapi/apiinlinelvlsdt) and [ApiBlockLvlSdt](https://api.onlyoffice.com/officeapi/textdocumentapi/apiblocklvlsdt).
oTable.GetCell(...).GetContent().GetElement(...) in base case returns [ApiParagraph](https://api.onlyoffice.com/officeapi/textdocumentapi/apiparagraph), which doesn't have GetTag method.

Could you send your script in full?
And could you run script below in your document and attach the result, please?
```js
let oDocument = Api.GetDocument();
let oParagraph = Api.CreateParagraph();

let oCell;
let oTable = oDocument.GetAllTablesOnPage(0)[0];
for (let i=0; i<oTable.GetRowsCount(); i++) {
    for (let j=0; j<oTable.GetRow(i).GetCellsCount(); j++) {
        oCell = oTable.GetCell(i, j).GetContent();
        oParagraph.AddText(oCell.GetElementsCount() + " " + oCell.GetElement(0).GetClassType());
        oParagraph.AddLineBreak();
    }
}
oDocument.Push(oParagraph);
```

**Comment by LiangKuan4451** [comment]
Before you replied to me, I already knew what the problem was and how to solve it. Your answer confirmed the issue. Inserting text into the document only creates a Paragraph. To use GetTag in a cell, you must first create an InlineLvlSdt or BlockLvlSdt.

I have a suggestion: your current documentation is very poor! Whether it’s the code examples or written tutorials, they often lack context and only cover the middle parts. This has left me unclear about the scenarios in which GetTag can be used. I can only explore it one by one through code suggestions in the macros, which is very time-consuming! I hope you can make the documentation more detailed.

Thank you for your support!

> 你好，@LiangKuan4451！ 我很抱歉，但我不确定我是否完全理解您的问题。 GetTag 方法仅适用于[ApiInlineLvlSdt](https://api.onlyoffice.com/officeapi/textdocumentapi/apiinlinelvlsdt)和[ApiBlockLvlSdt](https://api.onlyoffice.com/officeapi/textdocumentapi/apiblocklvlsdt)。 oTable.GetCell(...).GetContent().GetElement(...) 在基本情况下返回[ApiParagraph](https://api.onlyoffice.com/officeapi/textdocumentapi/apiparagraph)，它没有 GetTag 方法。
> 
> 您能发送完整的脚本吗？ 您可以在文档中运行下面的脚本并附上结果吗？
> 
> ```js
> let oDocument = Api.GetDocument();
> let oParagraph = Api.CreateParagraph();
> 
> let oCell;
> let oTable = oDocument.GetAllTablesOnPage(0)[0];
> for (let i=0; i<oTable.GetRowsCount(); i++) {
>     for (let j=0; j<oTable.GetRow(i).GetCellsCount(); j++) {
>         oCell = oTable.GetCell(i, j).GetContent();
>         oParagraph.AddText(oCell.GetElementsCount() + " " + oCell.GetElement(0).GetClassType());
>         oParagraph.AddLineBreak();
>     }
> }
> oDocument.Push(oParagraph);
> ```

Before you replied to me, I already knew what the problem was and how to solve it. Your answer confirmed the issue. Inserting text into the document only creates a Paragraph. To use GetTag in a cell, you must first create an InlineLvlSdt or BlockLvlSdt.

I have a suggestion: your current documentation is very poor! Whether it’s the code examples or written tutorials, they often lack context and only cover the middle parts. This has left me unclear about the scenarios in which GetTag can be used. I can only explore it one by one through code suggestions in the macros, which is very time-consuming! I hope you can make the documentation more detailed.

Thank you for your support!

**Comment by LiangKuan4451** [comment]
Before you replied to me, I already knew what the problem was and how to solve it. Your answer confirmed the issue. Inserting text into the document only creates a Paragraph. To use GetTag in a cell, you must first create an InlineLvlSdt or BlockLvlSdt.

I have a suggestion: your current documentation is very poor! Whether it’s the code examples or written tutorials, they often lack context and only cover the middle parts. This has left me unclear about the scenarios in which GetTag can be used. I can only explore it one by one through code suggestions in the macros, which is very time-consuming! I hope you can make the documentation more detailed.

Thank you for your support!

**Comment by lemonowl** [comment]
@LiangKuan4451
Thank you for your suggestion!
We are working on improving the documentation. 
If you have any specific ideas, feel free to share them on [api.onlyoffice.com](https://github.com/ONLYOFFICE/api.onlyoffice.com/issues)

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
