### ISSUE TITLE
Spellchecker nodehun fails to build with nodejs 12.10

### ISSUE THREAD

**Issue by onny** [ONLYOFFICE/DocumentServer#652]
Hey,
I'm trying to build the latest stable release, DocumentServer 5.4 using nodejs 12.10.
It fails with building the nodehun module, saying: "error: no matching function for call to ‘v8::Value::ToString()" etc.
Here's the complete log https://git.project-insanity.org/snippets/55
Downgrading to Nodejs 10.16 solves the issue.

Best regards,
Jonas

**Comment by ShockwaveNN** [comment]
Hi, can confirm. Same error with such Dockerfile

```
FROM onlyoffice/documentserver-ie

RUN apt-get -y update && apt-get -y install -y git make g++
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN rm -rf /var/www/onlyoffice/documentserver/server/SpellChecker/node_modules
RUN cd /var/www/onlyoffice/documentserver/server/SpellChecker/ && npm install
```

**Comment by ShockwaveNN** [comment]
We'll remove dependency of nodejs in future v5.5.0 release
All nodejs services packed to exe files using [pkg](https://github.com/zeit/pkg)

**Comment by ShockwaveNN** [comment]
DocumentServer v5.5.0 is released. This problem should be fixed.
