### ISSUE TITLE
Plugin cannot add content controls in version 5.5

### ISSUE THREAD

**Issue by raodienne** [ONLYOFFICE/DocumentServer#831]
**Do you want to request a *feature* or report a *bug*?**

Report a bug in docker container version 5.5.0.165 CE

**What is the current behavior?**

When trying to use a plugin to add a Content Control (https://api.onlyoffice.com/plugin/executemethod/addcontentcontrol) I receive a "errorEditingDownloadas" warning.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

`window.Asc.plugin.executeMethod("AddContentControl", [2, contentControl]);`

**My investigations**

The error seems to come from a function not defined in the API js.
`TypeError: this.Y9g is not a function -> sdk-all-min.js:1082:431`

It seems to correspond to [this line](https://github.com/ONLYOFFICE/sdkjs/blob/615987cb3d9eded08b9ba373ab222738eba7dfed/word/api_plugins.js#L167)

Which calls a method that seems to have been removed in [PR 744](https://github.com/ONLYOFFICE/sdkjs/pull/744/files)

Has it been replaced by another method ?

PS : I also saw a refactoring but it seems not relevant to the issue. I post it in case it helps : [here](https://github.com/ONLYOFFICE/sdkjs/commit/8f741a5b4e919ad1ba0b3afc96c3d74d1c04f6f7#diff-95550a3fe96adc8df36cc791a5fd39a5 )

**Did this work in previous versions of DocumentServer?**

Worked well with version 5.1.3.35. Should work prior to version 5.5 if my diagnosis is correct.

**DocumentServer version:**

Docker build 5.5.0.165

**Browser version:**

Firefox 74.0

**Comment by ShockwaveNN** [comment]
@flaminestone Please, take a look

**Comment by flaminestone** [comment]
I can confirm, it is bug (45094 in our internat bugtracker). We will fix it in future

**Comment by uwohlfeil** [comment]
I can reproduce this bug in Version **5.6.3 CE**  but not in the paid version **5.6.3 DE**. 
Is this a bug or is it not available in CE versions >=5.5?

**Comment by uwohlfeil** [comment]
@flaminestone Thanks for the information. 
Best regards

**Comment by ShockwaveNN** [comment]
Since DocumentServer v7.0.0 ContentControls available in opensource version so this problem should be resolved

**Comment by uwohlfeil** [comment]
It works now. Thank you very much.

**Comment by ShockwaveNN** [comment]
Sorry for a long wait )
