### ISSUE TITLE
After Update to 6.0.0 Error Message, cant open any Documents

### ISSUE THREAD

**Issue by leuedaniel** [ONLYOFFICE/DocumentServer#1024]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
After Update to Version 6.0.0 i cant open Power Point Document. It says that the presentation is loading but notting happens.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open a Power Point on my Nextcloud with Onlyoffice integration. It says that the presentation is loading but nothing happens.
out.log from docservice says:
[2020-10-15T11:00:40.339] [ERROR] nodeJS - changesError: docId = 600394075 Error: Uncaught TypeError: ic.YJb is not a function Script: https://office.hgverwaltung.ch/sdkjs/common/libfont/wasm/fonts.js Line: 37:318 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 platform: Win32 isLoadFullApi: false isDocumentLoadComplete: false StackTrace: TypeError: ic.YJb is not a function
    at https://office.hgverwaltung.ch/sdkjs/common/libfont/wasm/fonts.js:37:318
    at https://office.hgverwaltung.ch/sdkjs/common/libfont/wasm/fonts.js:37:325
**Did this work in previous versions of DocumentServer?**
Yes on 5.5.0 it works
**DocumentServer version:**
6.0.0
**Operating System:**
Ubuntu 20.04
**Browser version:**
Actual Google Chrome

**Comment by ShockwaveNN** [comment]
Hi, is this happened for any presentation of some some specific? Could you attach file for which error happens?

**Comment by leuedaniel** [comment]
with all powerpoint files where i've tested. an example is in attach
[Schulung Obmaenner.pptx](https://github.com/ONLYOFFICE/DocumentServer/files/5384163/Schulung.Obmaenner.pptx)

**Comment by ShockwaveNN** [comment]
Seems this file works fine for me on default Docker of `documentserver-ie`, do you have any custom fonts on your servers? 
if `documentserver-generate-allfonts.sh` failed?
![Uploading Screenshot from 2020-10-15 13-43-18.png…]()

**Comment by leuedaniel** [comment]
where i find this script documentserver-generate-allfonts.sh ?
No i dont have specially fonts, bevor the update to 6.0.0 it works

**Comment by ShockwaveNN** [comment]
```
/usr/bin/documentserver-generate-allfonts.sh
```

> No i dont have specially fonts, bevor the update to 6.0.0 it works

Yeah, it may work before, but we changed some code for fonts handling and some fonts who was fine in 5.6 maybe broken

If documentserver-generate-allfonts.sh is give no error - could you temporaly setup latest version on same os or use docker and check if this problem actual not for updating DocumentServer, or if you use clean setup

**Comment by leuedaniel** [comment]
no i've reinstalled the version 5.6. and it works

**Comment by ShockwaveNN** [comment]
Could you attach this file
https://doc-server-url/6.0.0-105/sdkjs/common/AllFonts.js

**Comment by leuedaniel** [comment]
I now works with docker
